version: '2'
services:
    nginx:
        image: nginx
        restart: unless-stopped
        volumes:
            - ./nginx_data/conf.d:/etc/nginx/conf.d
            - ./nginx_data/www-doanio:/var/www-doanio
        ports:
            - 80:80
